### ISSUE TITLE
Block miner address showing up as 0x000... on every block

### ISSUE THREAD

**Issue by cat-j** [poanetwork/blockscout#1548]
We're using BlockScout for a private PoA network and the _Miner_ field is displaying as 0x000... on all blocks, both on the BlockScout homepage and on each block's info page. Several people in my organisation have tried running the server locally and this has happened every single time; we think it might be a configuration issue, but we couldn't figure out which configuration file might be the culprit. We're running it with a Geth client.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
```Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]```
```Elixir 1.9.0-dev (d4f7f5e) (compiled with Erlang/OTP 21)```

* Operating System: Ubuntu 16.04 LTS

### Steps to reproduce

Set up BlockScout as detailed in README.md and connect it to a Geth node.

### Expected behaviour

Address should not be 0x000...

### Actual behaviour

Address is 0x000...

**Comment by vbaranov** [comment]
The same issue https://github.com/poanetwork/blockscout/issues/968 has been fixed. Do you use the code from the current `master` branch?

**Comment by cat-j** [comment]
I do. I tried cloning a clean, updated copy of the BlockScout repo and I'm still having this issue. Is there anything that I should fix by hand?

**Comment by cat-j** [comment]
I should add that it works fine on `production-rinkeby`!

**Comment by vbaranov** [comment]
Did you set `ETHEREUM_JSONRPC_VARIANT=geth` as described in README when you were building from `master` branch?

>Update your JSON RPC Variant in apps/explorer/config/dev.exs and apps/indexer/config/dev.exs. For variant, enter ganache, geth, or parity

**Comment by cat-j** [comment]
Yeah, I'm doing everything as described in README.

**Comment by vbaranov** [comment]
well, if `production-rinkeby` suits for you, please use it to deploy Blockscout. Moreover, the latest [release 1.3.4](https://github.com/poanetwork/blockscout/releases/tag/v1.3.4-beta) is already in that branch and we'll keep it updated with new releases.

**Comment by cat-j** [comment]
OK, turns out this started failing in a completely different way on `master` through no action of my own (fetched latest block just fine, froze on all the others), then displayed no blocks when I restarted the database, then magically started working. Since I never really touched the explorer, I'm leaning towards something dodgy going on with my node, so I guess you can close this.
