### ISSUE TITLE
Verify Contract 504 Gateway Timeout

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1872]
When I try to verify the following contract, I receive a 504 Gateway timeout: `0xb6fc6e2385d55ccb83e297bd92e2bd89795b47a3`

This contract does not have constructor arguments or libraries involved. 

### Steps to reproduce

1. Attempt to verify the contract
2. 504 timeout

**Comment by acravenho** [comment]
Here are a few more contracts where this is occurring:

* 0xe203e80bea7768028c5a91a6181dbe765391c3e0

**Comment by vbaranov** [comment]
@acravenho it may be something related to incorrect chosen evm version and this issue https://github.com/poanetwork/blockscout/issues/1653.

**Comment by acravenho** [comment]
@vbaranov 

* petersburg - `There was an error compiling your contract.`
* constantinople - `504 Gateway timeout`
* byzantium - `504 Gateway timeout`
* spariousDragon - `504 Gateway timeout`
* tangerineWhistle - `504 Gateway timeout`
* homestead - `504 Gateway timeout`

**Comment by ayrat555** [comment]
@acravenho this pr (https://github.com/poanetwork/blockscout/pull/2264) should fix the issue for contract verification using UI

**Comment by vbaranov** [comment]
I suppose the issue was resolved by background contract verification. I was able to verify both of the smart-contracts https://blockscout.com/eth/mainnet/address/0xb6fc6e2385d55ccb83e297bd92e2bd89795b47a3/contracts and https://blockscout.com/eth/mainnet/address/0xe203e80bea7768028c5a91a6181dbe765391c3e0/contracts with that feature. I installed it to the ETH Mainnet as a hotfix since it is not a part of a release yet. I think we can close this for now.

**Comment by Agilulfo1820** [comment]
Still have this issue. Trying to verify contract with this package: https://github.com/olivdb/truffle-source-verify#readme

**Comment by sirpy** [comment]
@vbaranov this issue is real and happening for many people on different deployments

**Comment by vbaranov** [comment]
@sirpy Blockscout provides 4 options for contracts verification through web interface and through API

<img width="558" alt="Screenshot 2021-12-29 at 14 35 25" src="https://user-images.githubusercontent.com/4341812/147658266-53538967-e7b7-42b3-af06-ab47ce04571a.png">

- Which option are you talking about?
- Which deployments are affected? Can you list?
- Which version of BlockScout is deployed on those instances?
- Steps to reproduce the issue: all the details for verification. Ideally, for contract which has been installed to one of the instances hosted by BlockScout team (Gnosis chain (testnet), Sokol, POA).

**Comment by sirpy** [comment]
@vbaranov thanks. I believe it is a timeout issue and hopefully the link you shared will resolve it.
this is about fuse.io explorer.
I didnt see those verification options, since which version do they exists?
is there a quick way to see on the UI via api which version is installed?

**Comment by vbaranov** [comment]
> I didnt see those verification options, since which version do they exists?

- Verification through Sourcify https://github.com/blockscout/blockscout/releases/tag/v3.7.0-beta
- Vyper contracts verification https://github.com/blockscout/blockscout/releases/tag/v4.0.0-beta
- Verification through Stanard Input JSON https://github.com/blockscout/blockscout/releases/tag/v4.1.0-beta

> is there a quick way to see on the UI via api which version is installed?

There is no such API. Version is given by environment variable and displayed in the left bottom corner in the footer.

**Comment by eric-convergence** [comment]
> > I didnt see those verification options, since which version do they exists?
> 
> * Verification through Sourcify https://github.com/blockscout/blockscout/releases/tag/v3.7.0-beta
> * Vyper contracts verification https://github.com/blockscout/blockscout/releases/tag/v4.0.0-beta
> * Verification through Stanard Input JSON https://github.com/blockscout/blockscout/releases/tag/v4.1.0-beta
> 
> > is there a quick way to see on the UI via api which version is installed?
> 
> There is no such API. Version is given by environment variable and displayed in the left bottom corner in the footer.

Hi @vbaranov , I found similar issue across the above-mentioned version and I suspect it is caused by the long running time of contract verification. May I know if I can extend the idle timeout time of the Blockscout API endpoint?
