### ISSUE TITLE
INVALID_ARGUMENT error for array argument when trying to use Write Contract feature

### ISSUE THREAD

**Issue by varasev** [poanetwork/blockscout#3486]
I'm getting an error `expected array value (argument="_whitelist", value="[\"0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D\"]", code=INVALID_ARGUMENT, version=abi/5.0.0-beta.153)` when clicking the Write button for the `setSendersWhitelist` function on the page https://blockscout.com/poa/xdai/address/0x5f849Fee27a1029fA5bDFA610677f95a82B47Eb8/write-contract

The input value is `["0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D"]`.

I also tried without quotes `[0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D]` and without brackets `0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D`.

<img src="https://user-images.githubusercontent.com/33550681/100358661-89d0d100-3007-11eb-93f2-1cca4a797e4c.png" width="400" />

**Comment by vbaranov** [comment]
@varasev it should be fixed now. Could you check at your side? You don't need to wrap in quotes or brackets

**Comment by varasev** [comment]
@vbaranov I still see the error when I try to pass an array of addresses there. Tried these cases:

- 0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D,0x1092a1E3A3F2FB2024830Dd12064a4B33fF8EbAe
- [0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D,0x1092a1E3A3F2FB2024830Dd12064a4B33fF8EbAe]
- "0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D","0x1092a1E3A3F2FB2024830Dd12064a4B33fF8EbAe"
- ["0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D","0x1092a1E3A3F2FB2024830Dd12064a4B33fF8EbAe"]

**Comment by vbaranov** [comment]
@varasev yes, sorry. xDai instance patched with the final fix. Could you check again?

**Comment by varasev** [comment]
Now it works fine except a case when we don't use `[`, `]` and quotes. I.e. it is fine for

- 0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D
- 0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D,0x1092a1E3A3F2FB2024830Dd12064a4B33fF8EbAe

But the error persists for

- "0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D"
- [0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D]
- [0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D,0x1092a1E3A3F2FB2024830Dd12064a4B33fF8EbAe]
- "0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D","0x1092a1E3A3F2FB2024830Dd12064a4B33fF8EbAe"
- ["0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D","0x1092a1E3A3F2FB2024830Dd12064a4B33fF8EbAe"]

I think we should make a text note to let users know which format is correct in case of `address[]` parameter because its behaviour differs from `remix`'es

**Comment by vbaranov** [comment]
I added support of square brackets for array input type. Thus, these inputs are correct:
- 0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D,0x1092a1E3A3F2FB2024830Dd12064a4B33fF8EbAe
- [0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D,0x1092a1E3A3F2FB2024830Dd12064a4B33fF8EbAe]

**Comment by varasev** [comment]
Could you also add support of quotes? Remix accepts the array as JSON input and it doesn't accept

[0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D,0x1092a1E3A3F2FB2024830Dd12064a4B33fF8EbAe]

but accepts

["0xb408e8217Aa6Bb2fEaD09FFCBAa505255573e04D","0x1092a1E3A3F2FB2024830Dd12064a4B33fF8EbAe"]

The users who used JSON or Remix would expect that the correct JSON formatted array should work on Blockscout as well.
